# Generated by Django 3.1.5 on 2021-08-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='model1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, verbose_name='city name')),
                ('lat', models.CharField(max_length=50, verbose_name='latitude')),
                ('lng', models.CharField(max_length=50, verbose_name='longitude')),
                ('country', models.CharField(default='India', editable=False, max_length=50, verbose_name='country name')),
                ('iso2', models.CharField(default='IN', editable=False, max_length=50, verbose_name='iso2')),
                ('admin', models.CharField(max_length=50, verbose_name='admin name')),
                ('capital', models.CharField(blank=True, max_length=50, verbose_name='capital name')),
                ('population', models.IntegerField(blank=True, verbose_name='population')),
                ('population_proper', models.IntegerField(blank=True, verbose_name='population proper')),
            ],
            options={
                'verbose_name_plural': 'App1',
                'ordering': ['city'],
            },
        ),
    ]
