# Generated by Django 3.1.5 on 2021-08-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20210822_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model1',
            name='capital',
            field=models.CharField(max_length=50, null=True, verbose_name='capital name'),
        ),
        migrations.AlterField(
            model_name='model1',
            name='population',
            field=models.IntegerField(null=True, verbose_name='population'),
        ),
        migrations.AlterField(
            model_name='model1',
            name='population_proper',
            field=models.IntegerField(null=True, verbose_name='population proper'),
        ),
    ]
